name: suur
description: "music player with class"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  flutter:
    sdk: flutter
  provider: ^6.1.5
  youtube_explode_dart: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
